// Pure generator for the AI-assistant context file (`AGENTS.md`) — no `vscode`
// import, so it's Node-testable. This is C7 part 1: ship OpenSNES/SNES knowledge
// into the project so any AI assistant (Copilot, Claude Code, Cursor…) that reads
// `AGENTS.md` becomes OpenSNES-expert. Facts are grounded in the OpenSNES SDK.

export interface AiContextOpts {
    /** project display name (e.g. the ROM base name). */
    projectName?: string;
    /** the ROM file name, if known (e.g. `game.sfc`). */
    romName?: string;
}

/**
 * Render the `AGENTS.md` for an OpenSNES project. Cross-assistant (Copilot reads
 * it behind a setting, Claude Code natively); Cooper also drops a
 * `.github/copilot-instructions.md` pointer for the guaranteed Copilot path.
 */
export function renderAgentsMd(opts: AiContextOpts = {}): string {
    const rom = opts.romName ?? 'the ROM';
    const name = opts.projectName ?? 'this project';
    return `# AGENTS.md — OpenSNES SNES game

Guidance for AI assistants working on **${name}**, a Super Nintendo (SNES) game
written in C for the **OpenSNES SDK**, compiled with **cc65816** (cproc → QBE →
wla-dx) and run/debugged on the **luna** cycle-accurate emulator. Generated by the
Cooper VS Code extension. These are hardware facts — follow them exactly.

## The compiler: cc65816 (this is not a normal C compiler)

- **\`int\` is 2 bytes (16-bit), not 4.** \`long\` is 4 bytes. Never assume 32-bit
  \`int\`. Prefer the **fixed-width types** \`u8/u16/u32\`, \`s8/s16/s32\` from
  \`<snes/types.h>\` — they are always correct. \`sizeof(int) == 2\`.
- The umbrella header is **\`#include <snes.h>\`** (pulls in the sub-headers).
- Pointers are small (near/far); do not assume a flat 32-bit address space.

## Building & running (Cooper does this for you)

- Build: \`make\` (Cooper passes \`OPENSNES=<sdk>\`). **Build/Run = release**;
  **Debug (F5) = a \`-g\` build** with source-level info. Don't hand-edit build
  artifacts (\`.pic\`/\`.pal\`/\`.map\`/\`.o\`/${rom}) — regenerate via \`make\`.
- Run/verify on hardware: **luna** (\`luna run …\`, or the \`luna mcp\` server —
  peek_memory/peek_vram/state/screenshot/run_until_pc, etc.). **Verify visual and
  state results in luna, not by reasoning** — it is cycle-accurate.

## SNES hardware constraints (enforce these)

### Colour / CGRAM
- 256 colours total, **15-bit BGR555**: \`RGB(r,g,b) = (b<<10)|(g<<5)|r\`, each
  channel **0–31**. There are only 32768 colours — never emit 24-bit RGB.
- CGRAM map: entries **0–127 = backgrounds, 128–255 = sprites** (8 sprite palettes
  of 16, sprite palette n at \`128 + n*16\`). **Colour 0 of each sub-palette is
  transparent.**
- Sub-palette size: **16** for 4bpp, **4** for 2bpp, **256** flat for 8bpp.

### Backgrounds (BG modes)
- Mode 0: 4 BGs × 2bpp (4 col). Mode 1: BG1/BG2 4bpp + BG3 2bpp (the common mode).
  Mode 3: BG1 8bpp + BG2 4bpp. Mode 7: 1 BG 8bpp, rotation/scaling.
- 2bpp = 4 colours, 4bpp = 16, 8bpp = 256. Tiles are **8×8**.
- Tilemaps: entries are 16-bit \`vhopppcc cccccccc\` — tile 0–1023, palette (bits
  10–12), priority (13), H-flip (14), V-flip (15). Legal map sizes: 32×32, 64×32,
  32×64, 64×64. Mode 7 map is 128×128 **bytes**, no per-cell attributes.

### Sprites (OBJ)
- **128 sprites** max, **32 per scanline**. Sprites are **always 4bpp (16
  colours)**, palette from CGRAM 128–255.
- OBSEL sizes are **pairs** (small/large), square: 8/16, 8/32, 8/64, 16/32, 16/64,
  32/64. Each sprite picks small or large.

### VRAM / OAM / DMA
- VRAM is 64 KB, word-addressed. OAM is 544 bytes (128 sprites + high table).
- Large transfers use DMA (\`dmaCopyVram\`, \`dmaCopyCGram\`), typically during
  vblank/forced-blank — do not write VRAM/CGRAM mid-frame expecting it to stick.

## Assets (edit sources, not binaries)

- Graphics source = an **indexed (256-colour) PNG**; \`gfx4snes\` converts it in
  the build to \`.pic\` (4bpp tiles) + \`.pal\` (BGR555) + optional \`.map\`. Edit
  the PNG (Cooper has palette + tile editors); \`make\` regenerates the binaries.
  Flags: \`-s\` size, \`-u\` colours-used (bpp), \`-o\` palette length, \`-m\` map.
- Tilemap **authoring** = Tiled (\`.tmj\`) → \`tmx2snes\`. Audio = \`smconv\`.

## How to work here

1. Write / edit C using the fixed-width types and the constraints above.
2. **Build with \`make\`** and fix any compiler/linker errors (they surface in the
   Problems panel).
3. **Run in luna and observe** — screenshot the framebuffer, read \`state\` /
   \`peek_vram\` / \`peek_memory\` — then self-correct. Ground every "does it work?"
   in luna's output, because \`int\`=2 and the PPU rules make host intuition wrong.
`;
}

/** The Copilot-guaranteed instructions file — points at AGENTS.md so there's one
 *  source of truth. */
export function renderCopilotInstructions(): string {
    return `# Copilot instructions

This is an **OpenSNES** SNES game (C, \`cc65816\`, run on the **luna** emulator).
See **\`AGENTS.md\`** at the repo root for the full hardware + SDK rules — follow
them exactly. Key gotcha: **\`int\` is 2 bytes**; use \`u8/u16/u32\`/\`s8/s16/s32\`.
Verify results in luna (cycle-accurate), not by reasoning.
`;
}
