// Pure OpenSNES clangd-config logic — no `vscode` import, so it is unit-testable
// under plain Node. The VS Code glue lives in extension.ts.

import * as fs from 'fs';
import * as path from 'path';

/**
 * clangd compile flags for OpenSNES, mirroring the SDK's own `clang -fsyntax-only`
 * lint pass (make/common.mk `CLANG_LINT_FLAGS` + `-I lib/include`). Deliberately
 * NO `-D__OPENSNES__`: on a 64-bit host that would mis-size `long`-backed `s32`.
 * See docs/clangd.md for the full `int`=2 caveat.
 */
export const CLANGD_EXTRA_FLAGS = [
    '-std=gnu11',
    '-Wno-pointer-to-int-cast',
    '-Wno-int-to-pointer-cast',
    '-Wno-unused-parameter',
];

/** A directory is an OpenSNES SDK root iff it has lib/include/snes.h. */
export function isOpenSnesRoot(dir: string): boolean {
    try {
        return fs.existsSync(path.join(dir, 'lib', 'include', 'snes.h'));
    } catch {
        return false;
    }
}

/**
 * Resolve the SDK path from an example/project Makefile's `OPENSNES` line.
 * Handles the canonical `OPENSNES := $(shell cd ../../.. && pwd)` form (all 30
 * SDK examples) plus literal/relative paths. Returns an absolute path or null.
 */
export function sdkPathFromMakefile(makefileText: string, makefileDir: string): string | null {
    const m = makefileText.match(/^[ \t]*OPENSNES[ \t]*[:?]?=[ \t]*(.+?)[ \t]*$/m);
    if (!m) {
        return null;
    }
    let val = m[1].trim();

    // Canonical form: $(shell cd <rel> && pwd)
    const shellMatch = val.match(/\$\(\s*shell\s+cd\s+(.+?)\s*&&\s*pwd\s*\)/);
    if (shellMatch) {
        return path.resolve(makefileDir, shellMatch[1].trim());
    }

    // Unresolvable make variable (other than the shell form above).
    if (val.includes('$')) {
        return null;
    }
    if (val.startsWith('~')) {
        val = path.join(process.env.HOME ?? '~', val.slice(1));
    }
    return path.isAbsolute(val) ? val : path.resolve(makefileDir, val);
}

/** Walk up from startDir looking for an SDK root (project may live in examples/). */
export function searchUpForSdk(startDir: string, maxLevels = 8): string | null {
    let dir = startDir;
    for (let i = 0; i < maxLevels; i++) {
        if (isOpenSnesRoot(dir)) {
            return dir;
        }
        const parent = path.dirname(dir);
        if (parent === dir) {
            break;
        }
        dir = parent;
    }
    return null;
}

export type SdkSource = 'setting' | 'makefile' | 'search';

/**
 * Detect the SDK path: explicit setting → project Makefile → upward search.
 * Returns the resolved path and how it was found, or null.
 */
export function detectSdk(opts: { configured?: string; projectDir: string }): { path: string; source: SdkSource } | null {
    const { configured, projectDir } = opts;

    if (configured && isOpenSnesRoot(configured)) {
        return { path: configured, source: 'setting' };
    }

    const mkPath = path.join(projectDir, 'Makefile');
    if (fs.existsSync(mkPath)) {
        const p = sdkPathFromMakefile(fs.readFileSync(mkPath, 'utf8'), projectDir);
        if (p && isOpenSnesRoot(p)) {
            return { path: p, source: 'makefile' };
        }
    }

    const up = searchUpForSdk(projectDir);
    if (up) {
        return { path: up, source: 'search' };
    }
    return null;
}

/** Render the `.clangd` YAML for a given SDK path. */
export function renderClangd(sdkPath: string): string {
    const inc = path.join(sdkPath, 'lib', 'include');
    return [
        '# .clangd — generated by Cooper (OpenSNES C support)',
        '# clangd uses the HOST target (int=4); on the SNES target int=2, so the',
        '# cc65816 build is the authority. Fixed-width types (u8/u16/...) are safe.',
        '# See docs/clangd.md.',
        'CompileFlags:',
        '  Add:',
        `    - "-I${inc}"`,
        '    - "-I."',
        ...CLANGD_EXTRA_FLAGS.map((f) => `    - "${f}"`),
        '',
    ].join('\n');
}
