// Pure project generator — no `vscode` import, Node-testable.
//
// Turns a resolved project spec (graphics mode + build flags + lib modules, from
// the game-type presets / the New Game wizard) into the two files a fresh
// OpenSNES project needs: a Makefile wired to the SDK contract, and a minimal,
// drift-safe starter main.c. The generated project builds with plain `make`
// (verified end-to-end by building it in the tests). Complements newProject.ts,
// which COPIES an SDK example; this GENERATES from a config.
//
// Grounded in make/common.mk (USE_* flags, LIB_MODULES, common.mk include) and a
// real minimal boot (text/hello_world + basics/fix32_orbit): consoleInit →
// setMode → oamInit(when sprites) → setMainScreen → setScreenOn → VBlank loop.

import { GraphicsConfig } from './snesModes';
import { GameTypeBuild } from './gameTypes';
import { Starter, DEFAULT_STARTER } from './starters';

export interface ProjectSpec {
    name: string;
    graphics: GraphicsConfig; // { mode 0..7, objSize 0..5 }
    build: GameTypeBuild; // { sound, sram?, hirom?, fastrom?, sa1?, superfx? }
    modules: string[]; // graphics/logic LIB_MODULES (flag-driven ones come from build)
}

/** Modules the hero-mover starter needs to link (added on top of the genre's). */
export const STARTER_MODULES = ['console', 'sprite', 'dma', 'input'];

/** SNES internal ROM title: upper-case, ≤21 chars (matches newProject.ts). */
export function romName(projectName: string): string {
    return projectName.toUpperCase().replace(/[^A-Z0-9 _-]/g, ' ').slice(0, 21).trim() || 'SNES GAME';
}

/**
 * Render the Makefile. `OPENSNES ?= <sdk>` (absolute) so plain `make` works and
 * detectSdk parses it. Only the enabled USE_* flags are emitted; the flag-driven
 * LIB_MODULES (snesmod/sram/superfx/sa1) are added by common.mk from those flags.
 */
export function renderMakefile(spec: ProjectSpec, sdkPath: string): string {
    const flags: string[] = ['USE_LIB     := 1'];
    if (spec.build.sound) {
        flags.push('USE_SNESMOD := 1');
    }
    if (spec.build.sram) {
        flags.push('USE_SRAM    := 1');
    }
    if (spec.build.hirom) {
        flags.push('USE_HIROM   := 1');
    }
    if (spec.build.fastrom) {
        flags.push('USE_FASTROM := 1');
    }
    if (spec.build.sa1) {
        flags.push('USE_SA1     := 1');
    }
    if (spec.build.superfx) {
        flags.push('USE_SUPERFX := 1');
    }
    return `# ${spec.name} — generated by Cooper.
OPENSNES ?= ${sdkPath}

TARGET   := ${spec.name}.sfc
ROM_NAME := ${romName(spec.name)}

${flags.join('\n')}
LIB_MODULES := ${spec.modules.join(' ')}
CSRC        := main.c

include $(OPENSNES)/make/common.mk
`;
}

/**
 * Render the starter main.c: a CONTROLLABLE placeholder hero on a genre-tinted
 * backdrop, so "New Game → Run" already moves something (A3 / dogfood F3/F13),
 * not a black screen. The `hero` sprite is wired by the caller through the
 * Add-Sprite pipeline (extern from data.asm, gfx4snes handles the tile layout);
 * loaded at a fixed 16px size — the project's objSize is for the user's real
 * sprites. Uses only stable core API (consoleInit/setMode/setColor/oam/padHeld).
 */
export function renderStarterMainC(spec: ProjectSpec, starter: Starter = DEFAULT_STARTER): string {
    const [r, g, b] = starter.backdrop;
    const L: string[] = [];
    L.push('#include <snes.h>');
    L.push('');
    L.push('// Placeholder hero — Cooper generated this so New Game → Run already moves');
    L.push('// something. Replace it with your own art via "Cooper: Add Sprite".');
    L.push('extern u8 hero[], hero_end[];');
    L.push('extern u8 hero_pal[], hero_pal_end[];');
    L.push('');
    L.push('int main(void) {');
    L.push('    u16 x = 120, y = 96;');
    L.push('');
    L.push('    consoleInit();');
    L.push(`    setMode(BG_MODE${spec.graphics.mode}, 0);`);
    L.push(`    setColor(0, RGB(${r}, ${g}, ${b}));   // ${starter.genre} backdrop`);
    L.push('');
    L.push('    oamInitGfxSet(hero, hero_end - hero, hero_pal, hero_pal_end - hero_pal, 0, 0x0000, OBJ_SIZE16_L32);');
    L.push('    setMainScreen(LAYER_OBJ);');
    L.push('');
    L.push('    WaitForVBlank();');
    L.push('    setScreenOn();');
    L.push('');
    L.push('    while (1) {');
    L.push('        u16 pad = padHeld(0);');
    L.push('        if ((pad & KEY_LEFT)  && x > 0)   x -= 2;');
    L.push('        if ((pad & KEY_RIGHT) && x < 240) x += 2;');
    if (starter.move === 'fourway') {
        L.push('        if ((pad & KEY_UP)    && y > 0)   y -= 2;');
        L.push('        if ((pad & KEY_DOWN)  && y < 208) y += 2;');
    }
    L.push('');
    L.push('        oamSet(0, x, y, 0, 0, 2, 0);   // frame 0 = the hero');
    L.push('        oamSetSize(0, OBJ_SMALL);');
    L.push(`        // ${starter.hint}`);
    L.push('        WaitForVBlank();');
    L.push('    }');
    L.push('    return 0;');
    L.push('}');
    return L.join('\n') + '\n';
}
