// Pure project generator — no `vscode` import, Node-testable.
//
// Turns a resolved project spec (graphics mode + build flags + lib modules, from
// the game-type presets / the New Game wizard) into the two files a fresh
// OpenSNES project needs: a Makefile wired to the SDK contract, and a minimal,
// drift-safe starter main.c. The generated project builds with plain `make`
// (verified end-to-end by building it in the tests). Complements newProject.ts,
// which COPIES an SDK example; this GENERATES from a config.
//
// Grounded in make/common.mk (USE_* flags, LIB_MODULES, common.mk include) and a
// real minimal boot (text/hello_world + basics/fix32_orbit): consoleInit →
// setMode → oamInit(when sprites) → setMainScreen → setScreenOn → VBlank loop.

import { GraphicsConfig } from './snesModes';
import { GameTypeBuild } from './gameTypes';

export interface ProjectSpec {
    name: string;
    graphics: GraphicsConfig; // { mode 0..7, objSize 0..5 }
    build: GameTypeBuild; // { sound, sram?, hirom?, fastrom?, sa1?, superfx? }
    modules: string[]; // graphics/logic LIB_MODULES (flag-driven ones come from build)
}

/** OBJ_SIZE_* macro names by OBSEL id (sprite.h #define order). */
const OBJ_SIZE_MACRO = ['OBJ_SIZE8_L16', 'OBJ_SIZE8_L32', 'OBJ_SIZE8_L64', 'OBJ_SIZE16_L32', 'OBJ_SIZE16_L64', 'OBJ_SIZE32_L64'];

/** SNES internal ROM title: upper-case, ≤21 chars (matches newProject.ts). */
export function romName(projectName: string): string {
    return projectName.toUpperCase().replace(/[^A-Z0-9 _-]/g, ' ').slice(0, 21).trim() || 'SNES GAME';
}

/**
 * Render the Makefile. `OPENSNES ?= <sdk>` (absolute) so plain `make` works and
 * detectSdk parses it. Only the enabled USE_* flags are emitted; the flag-driven
 * LIB_MODULES (snesmod/sram/superfx/sa1) are added by common.mk from those flags.
 */
export function renderMakefile(spec: ProjectSpec, sdkPath: string): string {
    const flags: string[] = ['USE_LIB     := 1'];
    if (spec.build.sound) {
        flags.push('USE_SNESMOD := 1');
    }
    if (spec.build.sram) {
        flags.push('USE_SRAM    := 1');
    }
    if (spec.build.hirom) {
        flags.push('USE_HIROM   := 1');
    }
    if (spec.build.fastrom) {
        flags.push('USE_FASTROM := 1');
    }
    if (spec.build.sa1) {
        flags.push('USE_SA1     := 1');
    }
    if (spec.build.superfx) {
        flags.push('USE_SUPERFX := 1');
    }
    return `# ${spec.name} — generated by Cooper.
OPENSNES ?= ${sdkPath}

TARGET   := ${spec.name}.sfc
ROM_NAME := ${romName(spec.name)}

${flags.join('\n')}
LIB_MODULES := ${spec.modules.join(' ')}
CSRC        := main.c

include $(OPENSNES)/make/common.mk
`;
}

/**
 * Render a minimal starter main.c: init the console, set the chosen BG mode,
 * init sprites (when the sprite module is in play), enable BG1 + the screen, and
 * run a VBlank-synced loop. Uses only stable core API (no drift surface); the
 * user fills the loop in.
 */
export function renderStarterMainC(spec: ProjectSpec): string {
    // Only call API whose module the generated project actually links.
    const usesSprites = spec.modules.includes('sprite');
    const usesBg = spec.modules.includes('background');
    const lines: string[] = [];
    lines.push('#include <snes.h>');
    lines.push('');
    lines.push('int main(void) {');
    lines.push('    consoleInit();');
    lines.push(`    setMode(BG_MODE${spec.graphics.mode}, 0);`);
    if (usesSprites) {
        lines.push(`    oamInit(${OBJ_SIZE_MACRO[spec.graphics.objSize]}, 0);`);
    }
    lines.push('');
    lines.push('    // TODO: load your tiles / palette / sprites here (see the Cooper snippets).');
    lines.push('');
    if (usesBg) {
        lines.push('    setMainScreen(LAYER_BG1);');
    }
    lines.push('    setScreenOn();');
    lines.push('');
    lines.push('    while (1) {');
    lines.push('        // TODO: your per-frame game logic.');
    lines.push('        WaitForVBlank();');
    lines.push('    }');
    lines.push('    return 0;');
    lines.push('}');
    return lines.join('\n') + '\n';
}
