// Pure "Add Sprite" scaffolding — no `vscode` import, Node-testable.
//
// Kills the dogfood #1 art→code cliff (F1/F2/F4): from an indexed sprite PNG,
// produce the three things a user otherwise hand-writes — the gfx4snes Makefile
// rule, the data.asm incbin bridge, and the C load snippet — with the tile
// number handled for them (oamInitGfxSet loads at a VRAM base so the sprite is
// tile 0; no `($2100-$2000)/16` arithmetic). Grounded in the SDK sprite examples
// (simple_sprite / animated_sprite) + gfx4snes -h.

const OBJ_SIZE_MACRO = ['OBJ_SIZE8_L16', 'OBJ_SIZE8_L32', 'OBJ_SIZE8_L64', 'OBJ_SIZE16_L32', 'OBJ_SIZE16_L64', 'OBJ_SIZE32_L64'];

/** A C identifier base derived from a PNG file name (e.g. `res/ship.png` → `ship`). */
export function symbolBase(pngPath: string): string {
    const stem = (pngPath.split(/[\\/]/).pop() ?? pngPath).replace(/\.[^.]+$/, '');
    const id = stem.replace(/[^A-Za-z0-9_]/g, '_').replace(/^([0-9])/, '_$1');
    return id || 'sprite';
}

/** The gfx4snes rule: `<pic> <pal>: <png>` (sprites are 4bpp = 16 colours). */
export function gfx4snesRule(pngRel: string, sizePx: number): string {
    const pic = pngRel.replace(/\.png$/i, '.pic');
    const pal = pngRel.replace(/\.png$/i, '.pal');
    return `${pic} ${pal}: ${pngRel}\n\t@echo "[GFX] $< -> sprite"\n\t@$(GFX4SNES) -s ${sizePx} -o 16 -u 16 -p -i $<\n`;
}

/** The data.asm section exporting `<base>`/`<base>_end`/`<base>_pal`/`<base>_pal_end`. */
export function dataAsmSection(base: string, pngRel: string): string {
    const pic = pngRel.replace(/\.png$/i, '.pic');
    const pal = pngRel.replace(/\.png$/i, '.pal');
    return `.section ".rodata_${base}" superfree\n`
        + `${base}:\n.incbin "${pic}"\n${base}_end:\n`
        + `${base}_pal:\n.incbin "${pal}"\n${base}_pal_end:\n.ends\n`;
}

/**
 * The C snippet: externs + a one-call load (oamInitGfxSet) + placing sprite
 * `oamId` at tile 0. `small` picks OBJ_SMALL/OBJ_LARGE within the project's
 * OBSEL pair. `vramAddr` must be 8KB-aligned (default 0x0000 for the first).
 */
export function loadSnippet(base: string, opts: { objSize: number; small: boolean; oamId?: number; vramAddr?: number }): string {
    const id = opts.oamId ?? 0;
    const vram = `0x${(opts.vramAddr ?? 0x0000).toString(16).toUpperCase().padStart(4, '0')}`;
    const size = OBJ_SIZE_MACRO[opts.objSize];
    return `// --- ${base}: generated by Cooper (Add Sprite) ---\n`
        + `// 1) at the top of the file (with the other externs):\n`
        + `extern u8 ${base}[], ${base}_end[];\n`
        + `extern u8 ${base}_pal[], ${base}_pal_end[];\n\n`
        + `// 2) in main(), after setMode and before setScreenOn:\n`
        + `oamInitGfxSet(${base}, ${base}_end - ${base}, ${base}_pal, ${base}_pal_end - ${base}_pal, 0, ${vram}, ${size});\n`
        + `oamSet(${id}, 120, 100, 0, 0, 3, 0);   // tile 0 (Cooper loaded it at the base)\n`
        + `oamSetSize(${id}, ${opts.small ? 'OBJ_SMALL' : 'OBJ_LARGE'});\n`;
}

/** Ensure `ASMSRC` in a Makefile includes `name` (add the line or extend it). */
export function ensureAsmSrc(makefile: string, name: string): string {
    const m = /^([ \t]*ASMSRC[ \t]*:?=[ \t]*)(.*)$/m.exec(makefile);
    if (!m) {
        // add an ASMSRC line just before the common.mk include.
        return makefile.replace(/^([ \t]*include\s+\$\(OPENSNES\)\/make\/common\.mk.*)$/m, `ASMSRC      := ${name}\n$1`);
    }
    const cur = m[2].trim().split(/\s+/).filter(Boolean);
    if (cur.includes(name)) {
        return makefile;
    }
    return makefile.replace(m[0], `${m[1]}${[...cur, name].join(' ')}`);
}

/** Append the gfx rule + the `combined.asm: <pic>` ordering dep (idempotent). */
export function appendGfxRule(makefile: string, pngRel: string, sizePx: number): string {
    const pic = pngRel.replace(/\.png$/i, '.pic');
    if (makefile.includes(`${pic} `) || makefile.includes(`${pic}:`)) {
        return makefile; // already wired
    }
    const rule = gfx4snesRule(pngRel, sizePx);
    const dep = `combined.asm: ${pic}\n`;
    return makefile.replace(/\s*$/, '\n') + '\n' + rule + dep;
}

/** Insert/append a data.asm section (idempotent by base). Creates the file body
 *  when `existing` is empty. */
export function upsertDataAsm(existing: string, base: string, pngRel: string): string {
    if (new RegExp(`^${base}:`, 'm').test(existing)) {
        return existing; // section already present
    }
    const header = existing.trim() ? existing.replace(/\s*$/, '\n\n') : '; data.asm — sprite/gfx incbin bridges (generated by Cooper).\n';
    return header + dataAsmSection(base, pngRel);
}
